name: Check if branch can be merged

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check-merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Fetch base branch
      run: git fetch origin ${{ github.base_ref }}

    - name: Check if branch can be merged
      run: |
        git checkout ${{ github.head_ref }}
        git merge origin/${{ github.base_ref }}
